/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class AccountManager {
  /** Loads or creates an accounts folder at the given `dir`. */
  static new(dir: string): Promise<AccountManager>
  stopIo(): Promise<void>
  startIo(): Promise<void>
  jsonrpcRequest(request: string): Promise<void>
  jsonrpcNextResponse(): Promise<string>
  getAccountIds(): Promise<Array<number>>
}
